# PyTorch基础

In [2]:
%matplotlib inline

In [149]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import torchvision

In [150]:
from pprint import pprint

import matplotlib.pyplot as plt
import numpy as np
from IPython.core.debugger import set_trace

# Tensors
- pytorch
- tf
- numpy
- ...  
所有数值计算的基础。

## numpy和pytorch中的Tensors的用法

In [5]:
import numpy as np
from numpy.linalg import inv
from numpy.linalg import multi_dot as mdot

In [151]:
# numpy
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
# torch
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [11]:
# numpy
X = np.random.random((5, 3))
X

array([[0.8312171 , 0.36179776, 0.01580835],
       [0.44063624, 0.06933639, 0.1822089 ],
       [0.18235466, 0.33677249, 0.22543197],
       [0.59661523, 0.53839349, 0.14819675],
       [0.8747109 , 0.89392354, 0.75322516]])

In [12]:
# pytorch
Y = torch.rand((5, 3))
Y

tensor([[0.4040, 0.5853, 0.0502],
        [0.5640, 0.7913, 0.9050],
        [0.3090, 0.4457, 0.8450],
        [0.2339, 0.7226, 0.0826],
        [0.2758, 0.9556, 0.9719]])

In [13]:
X.shape

(5, 3)

In [152]:
Y.shape, Y.size()

(torch.Size([5, 3]), torch.Size([5, 3]))

In [43]:
# numpy
np.matmul(X.T, X)
#X.T @ X

array([[2.03940429, 1.49583507, 0.88180728],
       [1.49583507, 1.3380877 , 0.84738628],
       [0.88180728, 0.84738628, 0.67357998]])

In [44]:
# torch
torch.matmul(Y.t(), Y)
#Y.t() @ Y

tensor([[0.7075, 1.2530, 1.0791],
        [1.2530, 2.6027, 2.1105],
        [1.0791, 2.1105, 2.4869]])

In [41]:
# numpy
inv(X.T @ X)

array([[ 2.97691304, -4.22923813,  1.42334215],
       [-4.22923813,  9.68422234, -6.64643298],
       [ 1.42334215, -6.64643298,  7.9826937 ]])

In [42]:
# torch
torch.inverse(Y.t() @ Y)

tensor([[10.0837, -4.1899, -0.8197],
        [-4.1899,  2.9730, -0.7050],
        [-0.8197, -0.7050,  1.3560]])

## 更多PyTorch Tensors

常用运算方法作为Tensors Class的method  
`.add()`

In [153]:
A = torch.eye(3)
A.add(1)

tensor([[2., 1., 1.],
        [1., 2., 1.],
        [1., 1., 2.]])

In [155]:
A

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

inplace运算方法，`.add_()`

In [156]:
A.add_(1)
A

tensor([[2., 1., 1.],
        [1., 2., 1.],
        [1., 1., 2.]])

## Indexing和broadcasting
和numpy原理相同

In [157]:
A = torch.eye(3)
A

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [158]:
A[0, 0]

tensor(1.)

In [59]:
A[0]

tensor([1., 0., 0.])

In [60]:
A[0:2]

tensor([[1., 0., 0.],
        [0., 1., 0.]])

In [61]:
A[:, 1:3]

tensor([[0., 0.],
        [1., 0.],
        [0., 1.]])

In [62]:
A + 1

tensor([[2., 1., 1.],
        [1., 2., 1.],
        [1., 1., 2.]])

In [63]:
A + torch.tensor([1,0,0])

tensor([[2., 0., 0.],
        [1., 1., 0.],
        [1., 0., 1.]])

## pytorch和numpy Tensors之间转换

In [159]:
A = torch.eye(3)
A

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [160]:
# torch --> numpy
B = A.numpy()
B

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)

注意: torch变量和numpy变量可以共享内存

In [162]:
#修改变量A，B也跟着变了
A.add_(.5)
A

tensor([[1.5000, 0.5000, 0.5000],
        [0.5000, 1.5000, 0.5000],
        [0.5000, 0.5000, 1.5000]])

In [163]:
B

array([[1.5, 0.5, 0.5],
       [0.5, 1.5, 0.5],
       [0.5, 0.5, 1.5]], dtype=float32)

In [74]:
# numpy --> torch
torch.from_numpy(np.eye(3))

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]], dtype=torch.float64)

## 现在使用GPU

In [164]:
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
device

device(type='cpu')

假如你的机器上装有GPU，可以看到: 
`device(type='cuda', index=0)`

将数据移到GPU上 `.to(device)`.

In [165]:
data = torch.eye(3)
data.to(device)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

注意：此时，所有计算发生在GPU上

In [166]:
res = data + data
res

tensor([[2., 0., 0.],
        [0., 2., 0.],
        [0., 0., 2.]])

In [167]:
res.device

device(type='cpu')

# 自动求导 `.backward()`

你只需要`torch.ones(3, requires_grad=True)`

参考:
- https://pytorch.org/docs/stable/autograd.html
- https://pytorch.org/tutorials/beginner/blitz/autograd_tutorial.html

求$y = x ^ 2$的导数

In [132]:
x = torch.tensor(2.)
x

tensor(2.)

In [169]:
#先定义变量x是可导的
x = torch.tensor(2., requires_grad=True)
x

tensor(2., requires_grad=True)

In [170]:
print(x.requires_grad)

True


In [171]:
print(x.grad)

None


In [172]:
y = x ** 2

print("导数 x:", x.grad)

导数 x: None


In [175]:
##多次运行会发生什么？
y = x ** 2
y.backward()

print("导数 x:", x.grad)

导数 x: tensor(12.)


In [176]:
x = torch.tensor(2., requires_grad=False)
x.backward()

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [177]:
# 推断时，关掉自动求导机制

params = torch.tensor(2., requires_grad=True)
#。。。更新参数

with torch.no_grad():
    y = x * x
    print(x.grad_fn)

None


# 练习
- 使用梯度下降法求解线性回归